#!/usr/bin/env python

"""
This is a script that takes an ALOE report file and generates a CSV row. 

This script can be used in conjunction with the cat utility to compound an archive of results
for data analysis in spreadsheet software. Note that this is written in Python 3.
"""

__status__ = "Prototype"
__author__ = "Daniel Barella"
__email__ = "dan.barella@gmail.com"
__copyright__ = "Copyright (c) 2013 SCCL, University of Washington (http://depts.washington.edu/sccl)"
__license__ = "GPL"
__version__ = "0.1"

"""
Pseudocode run-through:

This script needs the report file generated by ALOE during training mode.
It then looks for the semicolons and puts each following number after a commma - CSV file!
It spits the final string out to the system. Use cat to put this into an output file.

Perhaps a bit later in development I can have this make a file, but then it'd be hard to run
batch processes.
"""

