/*
 * This file is part of ALOE.
 *
 * ALOE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * ALOE is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with ALOE.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2012 SCCL, University of Washington (http://depts.washington.edu/sccl)
 */
package etc.aloe.wt2013;

import etc.aloe.cscw2013.ResolutionImpl;
import etc.aloe.data.Message;
import etc.aloe.data.MessageSet;
import etc.aloe.data.Segment;
import etc.aloe.data.SegmentSet;
import etc.aloe.processes.SegmentResolution;
import java.util.Date;
import java.util.HashMap;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Tests for the HeatSegmentation class.
 * @author Dan Barella <dan.barella@gmail.com>
 */
public class HeatSegmentationTest {
    
    MessageSet messages;
    SegmentResolution sr;
    
    public HeatSegmentationTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
        messages = new MessageSet();

        long now = new Date().getTime();
        long second = 1 * 1000;
        long minute = 60 * 1000;
        long hour = 60 * minute;

        messages.add(new Message(0, new Date(now), "Alice", "it's"));
        messages.add(new Message(1, new Date(now + 5 * second), "Bob", "cow"));
        messages.add(new Message(2, new Date(now + 6 * second), "Bob", "time"));
        messages.add(new Message(3, new Date(now + 8 * second), "Bob", "noooooooo"));
        messages.add(new Message(4, new Date(now + minute + 10 * second), "Bob", "once"));
        messages.add(new Message(5, new Date(now + minute + 11 * second), "Alice", "upon"));
        messages.add(new Message(6, new Date(now + minute + 12 * second), "Alice", "a"));
        //messages.add(new Message(7, new Date(now + 23 * minute + 3 * second), "Alice", "time"));
        //messages.add(new Message(8, new Date(now + 25 * minute + 7 * second), "Alice", "CAT!", true));
        //messages.add(new Message(9, new Date(now + 27 * minute + 20 * second), "Alice", "BAT!", true));
        //messages.add(new Message(10, new Date(now + 44 * minute), "Bob", "Sat?", true));
        //messages.add(new Message(11, new Date(now + 24 * hour), "Jane", "Is anyone there?", true));
    }
    
    @After
    public void tearDown() {
    }
    
    /**
     * Test of segment method, of class HeatSegmentation.
     */
    @Test
    public void testCalculateOccurrences() {
        System.out.println("calculateOccurrences");
        
        HeatSegmentation instance = new HeatSegmentation(60);
        instance.setSegmentResolution( new ResolutionImpl() );
        
        HashMap<Integer, Integer> occurrenceMap = instance.calculateOccurrences(instance.sortByTime(messages.getMessages()));
        
        assertEquals(0, (int)occurrenceMap.get(0));
        assertEquals(1, (int)occurrenceMap.get(1));
        assertEquals(2, (int)occurrenceMap.get(2));
        assertEquals(3, (int)occurrenceMap.get(3));
        assertEquals(0, (int)occurrenceMap.get(4));
        assertEquals(1, (int)occurrenceMap.get(5));
        assertEquals(2, (int)occurrenceMap.get(6));
    }

    /**
     * Test of segment method, of class HeatSegmentation.
     */
    @Test
    public void testSegment() {
        System.out.println("segment");
        
        HeatSegmentation instance = new HeatSegmentation(60);
        instance.setSegmentResolution( new ResolutionImpl() );
        
        SegmentSet segments = instance.segment(messages);
        
        assertEquals(5, segments.size());

        //The first segment generated by HeatSeg will be empty
        Segment seg0 = segments.get(1);
        Segment seg1 = segments.get(2);
        Segment seg2 = segments.get(3);
        Segment seg3 = segments.get(4);

        assertEquals(2, seg0.getMessages().size());
        assertEquals(2, seg1.getMessages().size());
        assertEquals(2, seg2.getMessages().size());
        assertEquals(1, seg3.getMessages().size());

        assertEquals(messages.get(0), seg0.getMessages().get(0));
        assertEquals(messages.get(2), seg1.getMessages().get(0));
        assertEquals(messages.get(4), seg2.getMessages().get(0));
        assertEquals(messages.get(6), seg3.getMessages().get(0));
        
    }
}
